input_data_path: 'data/heart_cleveland_upload.csv'
model_path: 'models/model_RF.pkl'
metric_path: 'models/val_metrics_rf.json'

train_params:
  model_type: 'CatBoostClassifier' 
  random_state: 42
  params:
    depth: 2
    l2_leaf_reg: 3 
    learning_rate: 0.1

feature_params:
  categorical_features:
    - 'sex'
    - 'cp'
    - 'fbs'
    - 'restecg'
    - 'exang'
    - 'slope'
    - 'ca'
    - 'thal'
  numerical_features:
    - 'age'
    - 'trestbps'
    - 'chol'
    - 'thalach'
    - 'oldpeak'
  target_col: 'condition'
