name: CI for homework 1

defaults:
  run:
    working-directory: homework1

on:
  push:
    branches: "homework1"
  pull_request:
    branches: "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.7"
        
    - name: Install project
      run: |
        pip install -e src/
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --statistics
        
    - name: Test programm
      run: |
        pytest